#!/bin/sh

[ "$1" = get ] || exit 0

user=$(git config --get gh.user)
[ -n "$user" ] || exec gh auth git-credential get

token=$(gh auth token --user "$user") || exit 0
printf 'username=%s\npassword=%s\n' "$user" "$token"
