# Catppuccin Mocha for fuzzel
# Licensed under MIT (https://github.com/catppuccin/fuzzel/blob/main/LICENSE)

[main]
font=HackGen Console NF:size=14
dpi-aware=no
prompt="❯❯ "
terminal=wezterm

lines=16
width=50
tabs=4
horizontal-pad=50
vertical-pad=18
inner-pad=10

image-size-ratio=.25

keyboard-focus=on-demand
exit-on-keyboard-focus-loss=yes

[border]
width=1

[colors]
background=1e1e2edd
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=b4befeff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=b4befeff
counter=7f849cff
border=b4befeff
