add_newline = false

[character]
error_symbol = "[❯❯❯](bold red)"
success_symbol = "[❯❯❯](bold green)"
vicmd_symbol = "[❮❮❮](bold green)"

[cmd_duration]
format = "󱫌 [$duration]($style)"

[git_status]
disabled = true

[memory_usage]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
