[ids]
*

[main]
capslock = leftcontrol
a = lettermod(meta, a, 150, 200)
s = lettermod(alt, s, 150, 200)
d = lettermod(control, d, 150, 200)
f = lettermod(shift, f, 150, 200)

semicolon = lettermod(meta, semicolon, 150, 200)

[control:C]
a = C-a
s = C-s
d = C-d
f = C-f
semicolon = C-semicolon

[shift:S]
a = S-a
s = S-s
d = S-d
f = S-f
semicolon = S-semicolon

[alt:A]
a = A-a
s = A-s
d = A-d
f = A-f
semicolon = A-semicolon

